name       : scala
version    : 2.11.8
release    : 1
source     :
    - https://github.com/scala/scala/archive/v2.11.8.tar.gz : 4f11273b4b3c771019253b2c09102245d063a7abeb65c7b1c4519bd57605edcf
license    : BSD-3-Clause
component  : programming
summary    : Scala Language Toolchain
description: |
    Scala Language Toolchain
builddeps  :
    - apache-ant
    - git
build      : |
    ant build-opt pack.doc osgi.done -Dbuild.release=true
install    : |
    cd build/pack
    ls -lah man/man1
    install -d $installdir/usr/bin
    install -d $installdir/usr/share/scala
    cp -R lib $installdir/usr/share/scala
    for pak in fsc scala scalac scaladoc scalap; do
        install -D -m 00755 "bin/$pak" "$installdir/usr/share/scala/bin/$pak";
        ln -s "/usr/share/scala/bin/$pak" "$installdir/usr/bin/$pak";
        install -D -m 00644 "man/man1/$pak.1" "$installdir/usr/share/man/man1/$pak.1";
    done