name       : scala
version    : 2.13.2
release    : 5
source     :
    - https://github.com/scala/scala/archive/v2.13.2.tar.gz : 54fc3ef0c86534aafe7be9fb52daad18e82bbd920c4b90585c4f4f33cbb9274f
license    : BSD-3-Clause
component  : programming
summary    : Scala Language Toolchain
description: |
    Scala Language Toolchain
builddeps  :
    - git
    - openjdk-8-devel
    - sbt
rundeps    :
    - openjdk-8
networking : yes
build      : |
    # Unfortunately we need to build the whole doc to get manpages.
    sbt -Divy.home=$workdir/.ivy2 \
        -Dsbt.global.base=$workdir/.sbt \
        -Dsbt.ivy.home=$workdir/.ivy2 \
        -Duser.home=$workdir/.java \
        enableOptimizer package doc
install    : |
    cd build

    install -dm00755 $installdir/usr/share/scala
    cp -a pack/lib $installdir/usr/share/scala

    pushd pack/bin
    rm *.bat
    install -dm00755 $installdir/usr/bin
    for cmd in *; do
        # Set JAVACMD at line 2 of every command (i.e. after shabang)
        sed '2iJAVACMD=/usr/lib64/openjdk-8/bin/java' -i $cmd

        install -Dm00755 $cmd -t $installdir/usr/share/scala/bin
        ln -s /usr/share/scala/bin/$cmd $installdir/usr/bin/$cmd
    done
    popd

    cp -a quick/classes/scala-dist/man $installdir/usr/share
