name       : scala
version    : 2.13.5
release    : 8
source     :
    - https://github.com/scala/scala/archive/v2.13.5.tar.gz : dfb1102c0d6238663b2a082f299431ca6c2bb4191947e03e3c462007f01b03a1
license    : BSD-3-Clause
component  : programming
homepage   : https://www.scala-lang.org/
summary    : Scala Language Toolchain
description: |
    Scala combines object-oriented and functional programming in one concise, high-level language. Scala's static types help avoid bugs in complex applications, and its JVM and JavaScript runtimes let you build high-performance systems with easy access to huge ecosystems of libraries.
builddeps  :
    - git
    - openjdk-11-devel
    - sbt
rundeps    :
    - openjdk-11
networking : yes
build      : |
    export SBT_OPTS="-Xmx4G -XX:ReservedCodeCacheSize=64M"

    sbt -Divy.home=$workdir/.ivy2 \
        -Dsbt.global.base=$workdir/.sbt \
        -Dsbt.ivy.home=$workdir/.ivy2 \
        -Duser.home=$workdir/.java \
        enableOptimizer package dist/mkPack
install    : |
    cd build

    install -dm00755 $installdir/usr/share/scala
    cp -a pack/lib $installdir/usr/share/scala

    pushd pack/bin
    rm *.bat
    install -dm00755 $installdir/usr/bin
    for FILE in *; do
        install -Dm00755 $FILE -t $installdir/usr/share/scala/bin
        cp $pkgfiles/java-shim.sh $installdir/usr/bin/$FILE
        echo "/usr/share/scala/bin/$FILE \"\$@\"" >> $installdir/usr/bin/$FILE
    done
    popd

    cp -a quick/classes/scalaDist/man $installdir/usr/share
