name       : scala
version    : 2.12.4
release    : 4
source     :
    - https://github.com/scala/scala/archive/v2.12.4.tar.gz : 9d1eaf570f95204a8894ab941070354b1672904a903ae3d1b45df201ddd1ed7d
license    : BSD-3-Clause
component  : programming
summary    : Scala Language Toolchain
description: |
    Scala Language Toolchain
builddeps  :
    - git
    - openjdk-8-devel
    - sbt
rundeps    :
    - openjdk-8
networking : yes
build      : |
    sbt -Dsbt.global.base=./.sbt/ -Dsbt.ivy.home=./.ivy2/ -Divy.home=./.ivy2/ dist/mkPack publishDists
install    : |
    cd build/pack
    install -d $installdir/usr/bin
    install -d $installdir/usr/share/scala
    cp -R lib $installdir/usr/share/scala
    for pak in fsc scala scalac scaladoc scalap; do
        install -D -m 00755 "bin/$pak" "$installdir/usr/share/scala/bin/$pak";
        ln -s "/usr/share/scala/bin/$pak" "$installdir/usr/bin/$pak";
        install -D -m 00644 "../quick/classes/scala-dist/man/man1/$pak.1" "$installdir/usr/share/man/man1/$pak.1";
    done
