name       : scala
version    : 2.13.2
release    : 6
source     :
    - https://github.com/scala/scala/archive/v2.13.2.tar.gz : 54fc3ef0c86534aafe7be9fb52daad18e82bbd920c4b90585c4f4f33cbb9274f
license    : BSD-3-Clause
component  : programming
summary    : Scala Language Toolchain
description: |
    Scala Language Toolchain
builddeps  :
    - git
    - openjdk-11-devel
    - sbt
rundeps    :
    - openjdk-11
networking : yes
build      : |
    sbt -Divy.home=$workdir/.ivy2 \
        -Dsbt.global.base=$workdir/.sbt \
        -Dsbt.ivy.home=$workdir/.ivy2 \
        -Duser.home=$workdir/.java \
        enableOptimizer package dist/mkPack
install    : |
    cd build

    install -dm00755 $installdir/usr/share/scala
    cp -a pack/lib $installdir/usr/share/scala

    pushd pack/bin
    rm *.bat
    install -dm00755 $installdir/usr/bin
    for FILE in *; do
        install -Dm00755 $FILE -t $installdir/usr/share/scala/bin
        cp $pkgfiles/java-shim.sh $installdir/usr/bin/$FILE
        echo "/usr/share/scala/bin/$FILE \"\$@\"" >> $installdir/usr/bin/$FILE
    done
    popd

    cp -a quick/classes/scala-dist/man $installdir/usr/share
